name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - '[0-9]+.*'
jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
  create-release:
    name: "Create GitHub release"
    # only publish from the origin repository
    if: github.repository_owner == 'xd009642'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: publish package to crates
        run: |
          cargo package
          cargo publish --token ${{ secrets.CARGO_TOKEN }}
